# Generated by Django 3.2.5 on 2021-07-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourites',
            name='bools',
            field=models.BooleanField(default=False),
        ),
    ]
