# Generated by Django 3.2.5 on 2021-07-04 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nco', '0002_favourites_bools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='nco.news'),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
